- hosts: json_nodes
  become: yes
  vars:
    destination: ~/ec2-user/json
  tasks:
    - name: "install curl"
      yum:
        name: curl
        state: latest
    - name: "Run a command using a templated variable (always use quote filter to avoid injection)"
      shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
    - name: "install nodejs"
      yum:
        name: nodejs
        state: latest
    - name: "install gcc-c++ make"
      yum:
        name: gcc-c++,make
        state: latest
    - name: "clone repo with json-server"
      git:
        repo: "https://github.com/typicode/json-server.git"
        dest: "{{destination}}"
        clone: no
        update: yes
    - name: "Run npm command to install server"
      shell: npm install -g json-server
    - name: 'copy db.json'
      file:
        src: "db.json"
        dest: "{{destination}}"
        state: link
        force: yes
    - name: "watch on localhost ur db"
      shell: json-server --watch db.json